Table usuario [headercolor: #175e7a] {
	id_usuario integer [ pk, not null ]
	primer_nombre varchar [ not null ]
	segundo_nombre varchar
	primer_apellido varchar(255) [ not null ]
	segundo_apellido varchar(255)
	correo_electronico varchar [ not null, unique ]
	fecha_registro date [ not null ]
	salario_mensual_base decimal [ not null ]
	estado boolean [ not null ]
	creado_por integer [ not null ]
	modificado_por integer [ not null ]
	creado_en timestamp [ not null ]
	modificado_en timestamp [ not null ]
}

Table presupuesto [headercolor: #175e7a] {
	id_presupuesto integer [ pk, not null ]
	id_usuario integer [ not null ]
	nombre_descriptivo varchar
	anio_inicio integer [ not null ]
	mes_inicio integer [ not null ]
	anio_fin integer [ not null ]
	mes_fin integer [ not null ]
	total_ingresos_planificados decimal [ not null ]
	total_gastos_planificados decimal [ not null ]
	total_ahorro_planificado decimal [ not null ]
	fecha_hora_creacion timestamp [ not null ]
	estado varchar [ not null ]
	creado_por integer [ not null ]
	modificado_por integer [ not null ]
	creado_en timestamp [ not null ]
	modificado_en timestamp [ not null ]
}

Table categoria [headercolor: #175e7a] {
	id_categoria integer [ pk, not null ]
	nombre_categoria varchar [ not null ]
	descripcion varchar
	tipo_categoria varchar [ not null ]
	nombre_icono varchar [ not null ]
	color_hex varchar
	orden_presentacion integer [ not null ]
	creado_por integer [ not null ]
	modificado_por integer [ not null ]
	creado_en timestamp [ not null ]
	modificado_en timestamp [ not null ]
}

Table subcategoria [headercolor: #175e7a] {
	id_subcategoria integer [ pk, not null ]
	id_categoria integer [ not null ]
	nombre_subcategoria varchar [ not null ]
	descripcion varchar
	esta_activa boolean [ not null ]
	es_por_defecto boolean [ not null ]
	creado_por integer [ not null ]
	modificado_por integer [ not null ]
	creado_en timestamp [ not null ]
	modificado_en timestamp [ not null ]
}

Table presupuesto_detalle [headercolor: #175e7a] {
	id_presupuesto_detalle integer [ pk, not null ]
	id_presupuesto integer [ not null ]
	id_subcategoria integer [ not null ]
	monto_mensual decimal [ not null ]
	observaciones varchar
	creado_por integer [ not null ]
	modificado_por integer [ not null ]
	creado_en timestamp [ not null ]
	modificado_en timestamp [ not null ]
}

Table obligacion_fija [headercolor: #175e7a] {
	id_obligacion integer [ pk, not null ]
	id_usuario integer [ not null ]
	id_subcategoria integer [ not null ]
	nombre_obligacion varchar [ not null ]
	descripcion varchar
	monto_fijo_mensual decimal [ not null ]
	dia_vencimiento integer [ not null ]
	esta_vigente boolean [ not null ]
	fecha_inicio date [ not null ]
	fecha_fin date [ not null ]
	creado_por integer [ not null ]
	modificado_por integer [ not null ]
	creado_en timestamp [ not null ]
	modificado_en timestamp [ not null ]
}

Table transaccion [headercolor: #175e7a] {
	id_transaccion integer [ pk, not null ]
	id_usuario integer [ not null ]
	id_presupuesto integer [ not null ]
	anio integer [ not null ]
	mes integer [ not null ]
	id_subcategoria integer [ not null ]
	id_obligacion integer [ not null ]
	tipo_transaccion varchar [ not null ]
	descripcion varchar
	monto decimal [ not null ]
	fecha_movimiento date [ not null ]
	metodo_pago varchar [ not null ]
	numero_factura varchar [ not null ]
	observaciones varchar
	fecha_hora_registro timestamp [ not null ]
	creado_por integer [ not null ]
	modificado_por integer [ not null ]
	creado_en timestamp [ not null ]
	modificado_en timestamp [ not null ]
}

Ref fk_presupuesto_id_usuario_usuario {
	presupuesto.id_usuario > usuario.id_usuario [ delete: no action, update: no action ]
}

Ref fk_subcategoria_id_categoria_categoria {
	subcategoria.id_categoria > categoria.id_categoria [ delete: no action, update: no action ]
}

Ref fk_presupuesto_detalle_id_presupuesto_presupuesto {
	presupuesto_detalle.id_presupuesto > presupuesto.id_presupuesto [ delete: no action, update: no action ]
}

Ref fk_presupuesto_detalle_id_subcategoria_subcategoria {
	presupuesto_detalle.id_subcategoria > subcategoria.id_subcategoria [ delete: no action, update: no action ]
}

Ref fk_obligacion_fija_id_usuario_usuario {
	obligacion_fija.id_usuario > usuario.id_usuario [ delete: no action, update: no action ]
}

Ref fk_obligacion_fija_id_subcategoria_subcategoria {
	obligacion_fija.id_subcategoria > subcategoria.id_subcategoria [ delete: no action, update: no action ]
}

Ref fk_transaccion_id_usuario_usuario {
	transaccion.id_usuario > usuario.id_usuario [ delete: no action, update: no action ]
}

Ref fk_transaccion_id_presupuesto_presupuesto {
	transaccion.id_presupuesto > presupuesto.id_presupuesto [ delete: no action, update: no action ]
}

Ref fk_transaccion_id_subcategoria_subcategoria {
	transaccion.id_subcategoria > subcategoria.id_subcategoria [ delete: no action, update: no action ]
}

Ref fk_transaccion_id_obligacion_obligacion_fija {
	transaccion.id_obligacion > obligacion_fija.id_obligacion [ delete: no action, update: no action ]
}